// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUclmdwtrTHm_3Pq4tnpm871WiZAQBON8',
    appId: '1:276525832875:web:6a30b2e06399e7a34975ee',
    messagingSenderId: '276525832875',
    projectId: 'appstone-db',
    authDomain: 'appstone-db.firebaseapp.com',
    storageBucket: 'appstone-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiP35vxdY70FaS6TR1GN1ahe09ZV3oRNk',
    appId: '1:276525832875:android:f4f5ffc66a5c01184975ee',
    messagingSenderId: '276525832875',
    projectId: 'appstone-db',
    storageBucket: 'appstone-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlv66B0ZPaYgchSrhY3u1maoUpLn2TZHk',
    appId: '1:276525832875:ios:f579852692a610bc4975ee',
    messagingSenderId: '276525832875',
    projectId: 'appstone-db',
    storageBucket: 'appstone-db.firebasestorage.app',
    iosBundleId: 'com.example.appstone',
  );
}
